// Shipping related types
import { MLSellerAddress } from "@/types/ml/location.types";
import { MLShipping } from "@/types/ml/shipping.types";
import { MLOriginalSaleTerm, MLSaleTerm } from "@/types/ml/sale-terms.types";
import { MLAttribute, MLOriginalAttribute } from "@/types/ml/attributes.types";
import { MLOriginalPicture, MLPicture } from "@/types/ml/pictures.types";

export interface MLOriginalData {
  id: string;
  site_id: string;
  title: string;
  seller_id: number;
  category_id: string;
  official_store_id: number;
  price: number;
  base_price: number;
  original_price: null;
  currency_id: string;
  initial_quantity: number;
  sale_terms: MLOriginalSaleTerm[];
  buying_mode: string;
  listing_type_id: string;
  condition: string;
  permalink: string;
  thumbnail_id: string;
  thumbnail: string;
  pictures: MLOriginalPicture[];
  video_id: null;
  descriptions: any[];
  accepts_mercadopago: boolean;
  non_mercado_pago_payment_methods: any[];
  shipping: MLShipping;
  international_delivery_mode: string;
  seller_address: MLSellerAddress;
  seller_contact: null;
  location: Record<string, never>;
  coverage_areas: any[];
  attributes: MLOriginalAttribute[];
  listing_source: string;
  variations: any[];
  status: string;
  sub_status: any[];
  tags: string[];
  warranty: string;
  catalog_product_id: string;
  domain_id: string;
  parent_item_id: null;
  deal_ids: any[];
  automatic_relist: boolean;
  date_created: string;
  last_updated: string;
  health: null;
  catalog_listing: boolean;
}

// Main Product type
export interface MLProduct {
  id: number;
  mlId: string;
  siteId: string;
  title: string;
  sellerId: number;
  categoryId: string;
  officialStoreId: number;
  price: string;
  basePrice: string;
  originalPrice: null;
  currencyId: string;
  initialQuantity: number;
  buyingMode: string;
  listingTypeId: string;
  condition: string;
  permalink: string;
  thumbnailId: string;
  thumbnail: string;
  videoId: null;
  acceptsMercadopago: boolean;
  shipping: MLShipping;
  internationalDeliveryMode: string;
  sellerAddress: MLSellerAddress;
  sellerContact: null;
  location: Record<string, never>;
  coverageAreas: any[];
  status: string;
  subStatus: any[];
  tags: string[];
  warranty: string;
  catalogProductId: string;
  domainId: string;
  parentItemId: null;
  dealIds: any[];
  automaticRelist: boolean;
  dateCreated: string;
  lastUpdated: string;
  health: null;
  catalogListing: boolean;
  originalData: MLOriginalData;
  createdAt: string;
  updatedAt: string;
  pictures: MLPicture[];
  attributes: MLAttribute[];
  saleTerms: MLSaleTerm[];
}